### ISSUE TITLE
Missing native functions

### ISSUE THREAD

**Issue by folknor** [phonon/language-galaxy#3]
Hi,

Lotv introduced lots of new native Blizzard functions that are missing from entity.name.function.native.galaxy. You can find them all here: http://hastebin.com/elenaxozeq.java

I could list them all here but I bet you have a script to convert natives.galaxy anyway :-)

**Comment by phonon** [comment]
Along with native functions, I'm also aware that I'm missing libNtve_gf_... functions along with Blizzard functions implemented in HoTS. Do you know which mpq file has these functions?

Thanks.

**Comment by folknor** [comment]
Yes, they are here: http://hastebin.com/elenaxozeq.java

Here is nvtelib: http://hastebin.com/pevuyetuki.coffee
and the header: http://hastebin.com/egufunuvad.cs

**Comment by phonon** [comment]
I actually managed to find the libLibty, libHots, and libVoid builtins in the SC2Data, will be adding snippets and grammar matching shortly.

**Comment by folknor** [comment]
Yeah, you mean these 3:
http://hastebin.com/gabakebevo.cs
http://hastebin.com/keqarusibu.cs
http://hastebin.com/edogexapuj.cs

But the most important one if you are adding all that crap is libVCMI: http://hastebin.com/adisepefoj.md
Which is VoidCampaignMissionLibrary.

There's also VCST: http://hastebin.com/ejawanepir.md
and VCUI: http://hastebin.com/futakulado.md

**Comment by folknor** [comment]
Seriously, just add natives.galaxy stuff and forget the rest please. It's way too much overhead and will only cause CPU and memory usage in Atom to spike.

**Comment by phonon** [comment]
Updated to lotv natives.galaxy and added library functions from:
- NativeLib_h.galaxy
- LibertyLib_h.galaxy
- SwarmLib_h.galaxy
- VoidLib_h.galaxy.

I'm only going to keep the builtin functions from these four libraries (and AI.galaxy) because I agree with you that the campaign libraries have a lot of overhead and not much use. These four libraries however do have useful functions that I use regularly and are very small compared to natives.galaxy. FYI I also updated [my script I've been using to parse Blizzard functions](https://gist.github.com/nmosfet/d8ec8a2f2cd9402b2ca7).

If the constants and functions updated are satisfactory, I'll proceed to close the missing constants and functions issues.

Thanks!

**Comment by folknor** [comment]
But surely CampaignLib_h.galaxy from libertystory.sc2campaign is useful?
Problem is that LibVCMI from Void superceeds it.

In any case they are both more useful than LibertyLib, SwarmLib and VoidLib combined.

**Comment by folknor** [comment]
Constants seem to be missing from core.sc2mod/base.sc2data/triggerlibs/gamedata/
I think the most useful ones there are Unit.galaxy and GameData.galaxy, but obviously that all depends on your project.

**Comment by phonon** [comment]
Based on browsing the the libVCMI from http://hastebin.com/adisepefoj.md, it seems like while some of the functions seem like useful general purpose functions, many are also campaign specific functions. Most of the constants are campaign specific and likely have little use outside of it.

The functions from Liberty, Swarm, and Void libs are general purpose functions. I use some of these in one of my own projects, hence I believe these are useful and should be included.

**Comment by folknor** [comment]
What I am trying to illustrate is that that's your opinion. I, and I am sure others as well depending on their Arcade project, find CampaignLib/LibVCMI more useful than Void/Liberty/Hots libs.

It's your project, and to be honest I do not care what is included after natives.galaxy and libnvte.
What I am saying is that objectively, either:
- none of it should be included except core.sc2mod (natives.galaxy / libnvte).
- all of it should be included

Again, though, and I must stress this:

I dont actually care.

**Comment by phonon** [comment]
Yeah I agree that the usefulness of the library functions depends on the project. However I disagree with either including everything or being as minimalist as possible. I think a mix of things should be added, although I do acknowledge this is inevitably based on my personal development preferences.

I added constants from GameData.galaxy. Aside from that, I am going to keep functions from Liberty, Swarm, and Void libraries (and the native libs).

Closing the issue since natives functions have been updated.

Thanks!
